name: OnlyCam
options:
  bundleIdPrefix: com.anton
targets:
  OnlyCam:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: 
      - Sources
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_NSCameraUsageDescription: "Камера нужна для трансляции."
      INFOPLIST_KEY_NSLocalNetworkUsageDescription: "Сеть нужна для подключения к ПК."